<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vendorinfo extends \Entities\Vendorinfo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'firstname', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'lastname', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'businesstitle', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'desc', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'registeredon', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'vendorid');
        }

        return array('__isInitialized__', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'firstname', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'lastname', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'businesstitle', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'desc', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'registeredon', '' . "\0" . 'Entities\\Vendorinfo' . "\0" . 'vendorid');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vendorinfo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', array($lastname));

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', array());

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setBusinesstitle($businesstitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusinesstitle', array($businesstitle));

        return parent::setBusinesstitle($businesstitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinesstitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinesstitle', array());

        return parent::getBusinesstitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesc($desc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesc', array($desc));

        return parent::setDesc($desc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesc', array());

        return parent::getDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegisteredon($registeredon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegisteredon', array($registeredon));

        return parent::setRegisteredon($registeredon);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegisteredon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegisteredon', array());

        return parent::getRegisteredon();
    }

    /**
     * {@inheritDoc}
     */
    public function setVendorid(\Entities\Vendor $vendorid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVendorid', array($vendorid));

        return parent::setVendorid($vendorid);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendorid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendorid', array());

        return parent::getVendorid();
    }

}
